name: Backup

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Run pg_dump
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: Run pg_dump
        run: |
          pg_dump --format=custom --compress=9 --dbname="${{ secrets.DATABASE_URL }}" --file="backup.dump"
      - name: Upload to Discord
        run: |
          export TODAY=$(date +%Y-%m-%d)
          mv backup.dump "backup_$TODAY.dump"
          curl --fail-with-body --silent -X POST \
            -F "payload_json={}" \
            -F "file0=@backup_$TODAY.dump" \
            ${{ secrets.DISCORD_WEBHOOK_URL }} > /dev/null
      - name: Remove backup directory
        run: |
          rm -f backup.dump
