name: Backup

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Run pg_dump
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: Create backup directory
        run: |
          mkdir -p ./backup
      - name: Run pg_dump
        run: |
          pg_dump --format=custom --compress=9 --dbname="${{ secrets.DATABASE_URL }}" --file="./backup/backup.dump" || exit 1
      - name: Upload to Dropbox
        run: |
          today=$(date +%Y-%m-%d)
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer ${{ secrets.DROPBOX_ACCESS_TOKEN }}" \
            --header "Dropbox-API-Arg: {\"path\": \"//$today.dump\",\"mode\": \"add\",\"autorename\": true,\"mute\": false}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @./backup/backup.dump || exit 1
      - name: Remove backup directory
        run: |
          rm -rf ./backup
